services:

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dokploy-network

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: api
        OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    expose:
      - 3000
    depends_on:
      - backend-api
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.http.services.frontend.loadbalancer.server.port=3000
      - traefik.http.routers.frontend.priority=1

  backend-api:
    build: ./backend-api
    expose:
      - 3001
    environment:
      - DB_SERVICE_HOST=backend-db
      - DB_SERVICE_PORT=3002
      - OTEL_SERVICE_NAME=backend-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    depends_on:
      - backend-db
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend-api.entrypoints=web
      - traefik.http.routers.backend-api.rule=PathPrefix(`/api`)
      - traefik.http.services.backend-api.loadbalancer.server.port=3001
      - traefik.http.middlewares.backend-api-strip.stripprefix.prefixes=/api
      - traefik.http.routers.backend-api.middlewares=backend-api-strip

  backend-db:
    build: ./backend-db
    expose:
      - 3002
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/demo
      - OTEL_SERVICE_NAME=backend-db
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    depends_on:
      - mongodb
    networks:
      - dokploy-network

  mongodb:
    image: mongo:latest
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true 

volumes:
  mongodb_data:
