receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - https://*.test.com
            - http://localhost:3000
          max_age: 7200
        endpoint: "0.0.0.0:4318"
        compression_algorithms: ["", "gzip"]

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
